name: Initial setup
on: 
  create:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    - uses: actions/checkout@master
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1
      with: 
        files: '["README.md","package.json"]'
      env:
        REPO: ${{ github.event.repository.name }}
        USER_OR_ORG: ${{ github.repository_owner }}
    - name: Update deps
      run: |
        npm install --save-dev denoify
        npm install --save-dev typescript
        npm install --save-dev evt
        rm package-lock.json
    - name: Commit files
      run: |
        git config --local user.email "joseph@semasim.com"
        git config --local user.name "garronej"
        git commit -m "Initial changes to the tamplate, may ${{ github.repository }} thrive ( via GH Action )" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
