name: Initial setup
on: 
  create:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Replace repository name
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: _REPOSITORY_NAME_
        replace: ${{ github.repository }}
    - name: Replace user or organization name
      uses: jacobtomlinson/gha-find-replace@master
      with: 
        find: _USER_OR_ORGANIZATION_
        replace: ${{ github.repository_owner }}
    - name: Commit files
      run: |
        git config --local user.email "joseph@semasim.com"
        git config --local user.name "garronej"
        git commit -m "Initial changes to the tamplate, may ${{ github.repository }} thrive ( via GH Action )" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
